/**
 * build.mjs
 * 将 public/ 目录下的静态资源打包为 src/assets.ts
 * 打包后，Worker 可同时提供前端静态文件与后端 API（单 Worker 部署）
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative, extname } from "node:path";
import { createHash } from "node:crypto";

// 根据文件内容生成短哈希，用作缓存破坏的版本号
function contentHash(buf) {
  return createHash("sha256").update(buf).digest("hex").slice(0, 10);
}

const PUBLIC_DIR = join(process.cwd(), "public");
const OUT = join(process.cwd(), "src", "assets.ts");

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".ico": "image/x-icon",
  ".webmanifest": "application/manifest+json",
};

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
    } else {
      out.push(full);
    }
  }
  return out;
}

const files = walk(PUBLIC_DIR).filter((f) => !extname(f) === false);

// 预计算 app.js / style.css 的内容哈希，用于注入到 index.html 的版本查询参数，
// 这样每次内容变化都会自动改变 ?v= 值，浏览器便会��新拉取，避免缓存到旧的前端。
const appBuf = readFileSync(join(PUBLIC_DIR, "app.js"));
const cssBuf = readFileSync(join(PUBLIC_DIR, "style.css"));
const appHash = contentHash(appBuf);
const cssHash = contentHash(cssBuf);

const entries = files.map((full) => {
  const rel = relative(PUBLIC_DIR, full).replace(/\\/g, "/");
  const url = "/" + rel;
  const mime = MIME[extname(full)] || "application/octet-stream";
  let content = readFileSync(full, "base64");
  // 对 index.html 注入内容哈希版本号，破坏浏览器缓存
  if (rel === "index.html") {
    let html = readFileSync(full, "utf-8");
    html = html.replace(/\/app\.js\?v=\d+/g, `/app.js?v=${appHash}`);
    html = html.replace(/\/style\.css\?v=\d+/g, `/style.css?v=${cssHash}`);
    content = Buffer.from(html, "utf-8").toString("base64");
  }
  return `  ["${url}", { contentType: "${mime}", data: "${content}" }]`;
});

const js = `/**
 * AUTO-GENERATED by build.mjs — 请勿手动修改。
 * 包含 public/ 目录的全部静态资源（base64 编码）。
 */
import type { AssetEntry } from "./asset-store";

export const assets: AssetEntry[] = [
${entries.join(",\n")}
];
`;

writeFileSync(OUT, js, "utf-8");
console.log(`✔ 已打包 ${files.length} 个静态文件 -> src/assets.ts`);
